### ISSUE TITLE
doesn't start any games

### ISSUE THREAD

**Issue by folkertvanheusden** [zakki/cgos#15] opened 2023-02-15 18:38 UTC
Hi,

When I start the python cgos implementation and let 2 gtp-programs connect, it won't start matches:

```
2023-02-15 19:36:42,256 - cgos_server - INFO - "(CGOS) 9x9 Computer Go Server" up and running at 2023-02-15 18:36:42 GMT
2023-02-15 19:36:42,256 - cgos_server - INFO - datafile:'/usr/local/games/cgos/server-python/wdata.txt' -> workdir:'/usr/local/games/cgos/server-python'
2023-02-15 19:36:42,273 - cgos_server - INFO - Serving on ('::', 9900, 0, 0), ('0.0.0.0', 9900)
2023-02-15 19:36:48,976 - cgos_server - INFO - Connection from ('172.29.0.107', 48970)
2023-02-15 19:36:59,396 - cgos_server - INFO - Connection from ('127.0.0.1', 39584)
2023-02-15 19:37:27,301 - cgos_server - INFO - Games in progress: 0
2023-02-15 19:37:27,301 - cgos_server - INFO - Batch rating
2023-02-15 19:37:27,302 - cgos_server - INFO - sizeof bad_users: 0
2023-02-15 19:37:27,302 - cgos_server - INFO - maximum skip elo: 2000.0
2023-02-15 19:37:27,302 - cgos_server - INFO - ELO permutation factor to be used: 3000.0
2023-02-15 19:37:42,317 - cgos_server - INFO - Batch rating
2023-02-15 19:37:42,317 - cgos_server - INFO - sizeof bad_users: 0
2023-02-15 19:37:42,318 - cgos_server - INFO - maximum skip elo: 2000.0
2023-02-15 19:37:42,318 - cgos_server - INFO - ELO permutation factor to be used: 3000.0
```

```
Python CGOS client. e1 cgosPython 0.3.0 beta (c)2009 Christian Nentwich
2023-02-15 19:36:47,970: Chose engine 1 ("DellaBaduck456a8b5") as next player. Switching and re-connecting.
2023-02-15 19:36:47,970: Starting GTP engine, command line: ../build/dellabaduck
2023-02-15 19:36:48,973: Attempting to connect to server '172.29.0.1', port 9900
2023-02-15 19:36:48,974: Connected
```

**Comment by zakki** [comment] 2023-02-16 04:16
If you are using `develop` branch, some fixes hasn't merged yet. Please try `genmove_analyze` branch.

Is there "Connection from ..." in server log?
https://github.com/zakki/cgos/blob/genmove_analyze/server-python/cgos/app/cgos.py#L1195

**Comment by folkertvanheusden** [comment] 2023-02-16 07:42
I do see "Connection  from", but then nothing happens - this is with the "genmove_analyze" branch!

```
2023-02-16 08:40:24,546 - cgos_server - INFO - "(CGOS) 9x9 Computer Go Server" up and running at 2023-02-16 07:40:24 GMT
2023-02-16 08:40:24,547 - cgos_server - INFO - datafile:'/usr/local/games/cgos/server-python/wdata.txt' -> workdir:'/usr/local/games/cgos/server-python'
2023-02-16 08:40:24,575 - cgos_server - INFO - Serving on ('0.0.0.0', 9900), ('::', 9900, 0, 0)
2023-02-16 08:40:30,794 - cgos_server - INFO - Connection from ('172.29.0.107', 41178)
2023-02-16 08:40:30,795 - cgos_server - DEBUG - S -> 0: '['protocol genmove_analyze']'
2023-02-16 08:40:30,796 - cgos_server - DEBUG - S ==> 0: 'protocol genmove_analyze
'
2023-02-16 08:40:30,797 - cgos_server - DEBUG - send queue 0: 0 protocol genmove_analyze

2023-02-16 08:40:47,041 - cgos_server - INFO - Connection from ('127.0.0.1', 41078)
2023-02-16 08:40:47,041 - cgos_server - DEBUG - S -> 1: '['protocol genmove_analyze']'
2023-02-16 08:40:47,042 - cgos_server - DEBUG - S ==> 1: 'protocol genmove_analyze
'
2023-02-16 08:40:47,042 - cgos_server - DEBUG - send queue 1: 0 protocol genmove_analyze

2023-02-16 08:41:09,597 - cgos_server - INFO - Games in progress: 0
2023-02-16 08:41:09,597 - cgos_server - INFO - Batch rating
2023-02-16 08:41:09,598 - cgos_server - INFO - sizeof bad_users: 0
2023-02-16 08:41:09,598 - cgos_server - INFO - maximum skip elo: 2000.0
2023-02-16 08:41:09,598 - cgos_server - INFO - ELO permutation factor to be used: 3000.0
2023-02-16 08:41:24,613 - cgos_server - INFO - Batch rating
2023-02-16 08:41:24,614 - cgos_server - INFO - sizeof bad_users: 0
2023-02-16 08:41:24,615 - cgos_server - INFO - maximum skip elo: 2000.0
2023-02-16 08:41:24,615 - cgos_server - INFO - ELO permutation factor to be used: 3000.0
```

**Comment by zakki** [comment] 2023-02-16 09:48
After that message in a server log, a DEBUG message "Server sent: protocol genmove_analyze" in a client log is expected.
https://github.com/zakki/cgos/blob/genmove_analyze/client-python/src/cgosclient.py#L495

What is your OS and OS version and python version?

```
2023-01-30 22:03:22,407 - INFO: Chose engine 1 ("KataGoV100") as next player. Switching and re-connecting.
2023-01-30 22:03:24,891 - INFO: Attempting to connect to server '127.0.0.1', port 1919
2023-01-30 22:03:24,892 - INFO: Connected
2023-01-30 22:03:24,892 - DEBUG: Server sent: protocol genmove_analyze
2023-01-30 22:03:24,892 - DEBUG: Responding: e1 cgosPython 0.3.1 beta genmove_analyze
2023-01-30 22:03:24,894 - DEBUG: Server sent: username
2023-01-30 22:03:24,895 - DEBUG: Responding: kata-v100
2023-01-30 22:03:24,895 - DEBUG: Server sent: password
2023-01-30 22:03:24,895 - DEBUG: Responding: mypw
2023-01-30 22:03:56,911 - DEBUG: Server sent: setup 2552 19 7.5 1800000 lz-v100(2167) kata-v100(2441)
2023-01-30 22:03:56,911 - INFO: Starting game against lz-v100(2167). Local engine ("KataGoV100", rated 2441) is playing black.
2023-01-30 22:03:56,912 - DEBUG: Server sent: genmove b 1800000
```

**Comment by folkertvanheusden** [comment] 2023-02-16 11:11
Oh maybe it is because I'm using the old client. I'll give the new client a
try.

I do see "protocol genmove_analyze" and my program does not respond to that.

OS: Linux (Debian for server, Ubuntu for clients)
Python: 3.10.4

**Comment by folkertvanheusden** [comment] 2023-02-16 11:25
Yes: I've now replaced the cgos-client program by the one in the python-cgos-server repo, and now things start to play.

So the conclusion is: the new cgos-server is not compatible with older clients, but that may be as designed?

**Comment by zakki** [comment] 2023-02-16 12:21
I have tested old tcl client and new python client, but I didn't tested old python clinet.
A tcl client and new python client sends a new line, but old python client does not.

Sending large analyze data without separator wouldn't work, so this's by design of some kind.
However, the incompatibility may cause problems when updates are applied to the server.

https://github.com/zakki/cgos/blob/genmove_analyze/client/cgosGtp.tcl#L419
https://github.com/zakki/cgos/commit/667602bef3234f34020c5b4ee501029e0480fd35#diff-e8b63f69b778b43dde6b8f3411ee3ccbf3c35a555ca6cd6e785cef4c9f68e8deL186

**Closed as completed** 2023-02-17 12:15 UTC

**Comment by zakki** [comment] 2023-02-17 14:02
I think this issue is fixed.
https://github.com/zakki/cgos/commit/5aff5458964e576771dfd6bd3b39c011061ccf31

I thought `StreamReader.read(n)` would block until n bytes were received, due to Python documentation translation.
